# Selenium Settings
selenium.browser=chrome
selenium.url=https://aquaguard-admin.web.app

# Appium Settings
appium.serverUrl=http://127.0.0.1:4723
appium.platformName=Android
appium.deviceName=Android Emulator
appium.automationName=UiAutomator2
appium.appPackage=com.aquaguard
appium.appActivity=com.aquaguard.MainActivity
appium.app=../frontend/app/build/outputs/apk/debug/app-debug.apk
